const recipe = (name, slots, tag = "", match = "") => ({ name, slots, tag, match });
const ingredient = (name, count = 1, tag = "", subtype = "") => ({
  name,
  count,
  tag,
  subtype,
});
const drink = (name, condition, rule) => ({ name, condition, rule });

export const CUSTOMER_VALUES = [
  1,
  1,
  2,
  2,
  3,
  3,
];

export const CUISINES = {
  italy: {
    id: "italy",
    flag: "🇮🇹",
    name: "Piazza Romana",
    region: "Italian restaurant",
    monogram: "PR",
    accent: "#3f7a4d",
    ability: "Perfect Pairing",
    abilityText: "Dishes with their exact pasta ingredient gain +1 serve value.",
    promotionText: "Lose the customer with an exact pasta pairing; track that pasta ingredient.",
    customerEffect: "Hand limit becomes 8 while refreshing.",
    recipes: [
      recipe("Farfalle al Salmone", 0),
      recipe("Fusilli Caprese", 0),
      recipe("Rigatoni alla Gricia", 0),
      recipe("Cannelloni Ricotta e Spinaci", 0),
      recipe("Spaghetti Carbonara", 1, "", "spaghetti"),
      recipe("Fettuccine Alfredo", 1, "", "fettuccine"),
      recipe("Lasagna Verde", 1, "", "lasagna"),
      recipe("Tagliatelle alla Bolognese", 1, "", "tagliatelle"),
      recipe("Cacio e Pepe", 1, "", "spaghetti"),
      recipe("Penne all'Arrabbiata", 1, "", "penne"),
      recipe("Penne al Pesto", 1, "", "penne"),
      recipe("Lasagna al Forno", 2, "", "lasagna"),
      recipe("Fettuccine ai Porcini e Tartufo", 2, "", "fettuccine"),
      recipe("Tagliatelle ai Funghi Porcini", 2, "", "tagliatelle"),
    ],
    ingredients: [
      ingredient("Spaghetti", 2, "pasta", "spaghetti"),
      ingredient("Fettuccine", 2, "pasta", "fettuccine"),
      ingredient("Tagliatelle", 2, "pasta", "tagliatelle"),
      ingredient("Lasagna Sheets", 2, "pasta", "lasagna"),
      ingredient("Penne", 2, "pasta", "penne"),
      ingredient("Campanelle", 1, "pasta", "campanelle"),
      ingredient("Gnocchi", 1, "pasta", "gnocchi"),
      ingredient("Ravioli", 1, "pasta", "ravioli"),
    ],
    flavors: ["Basil", "Balsamic Vinegar", "Parmigiano"],
    drinks: [
      drink("Cappuccino", "At least 1 recipe with its exact matching pasta Ingredient Card", "italyExact"),
      drink("Aperol Spritz", "At least 2 dishes with exactly 1 Ingredient Card each", "twoNormal"),
      drink("Limoncello", "At least 2 different pasta Ingredient Card types", "twoPasta"),
    ],
  },
  france: {
    id: "france",
    flag: "🇫🇷",
    name: "Le Petit Paris",
    region: "French restaurant",
    monogram: "LP",
    accent: "#3f55a5",
    ability: "Perfect Progression",
    abilityText: "Adjacent course pairs gain +1 each, to a maximum of +2.",
    promotionText: "Lose the customer with a course not already promoted; track that recipe.",
    customerEffect: "After the initial Refresh draw, you may replace your whole hand.",
    recipes: [
      recipe("Soupe à l'Oignon", 0, "entree"),
      recipe("Bouillabaisse", 0, "entree"),
      recipe("Garbure", 0, "entree"),
      recipe("Tourin", 0, "entree"),
      recipe("Quiche Lorraine", 1, "appetizer"),
      recipe("Escargots de Bourguignon", 1, "appetizer"),
      recipe("Salade Niçoise", 1, "appetizer"),
      recipe("Soufflé au Fromage", 1, "appetizer"),
      recipe("Ratatouille", 1, "main"),
      recipe("Boeuf Bourguignon", 1, "main"),
      recipe("Châteaubriand", 1, "main"),
      recipe("Croque Monsieur", 1, "main"),
      recipe("Pain Perdu", 2, "dessert"),
      recipe("Crème Brûlée", 2, "dessert"),
      recipe("Tarte Tatin", 2, "dessert"),
    ],
    ingredients: [
      ingredient("Shallots", 2),
      ingredient("Leeks", 2),
      ingredient("Carrots", 2),
      ingredient("Champignons de Paris", 2),
      ingredient("Gruyère", 2),
      ingredient("Apples", 2),
    ],
    flavors: ["Herbes de Provence", "Butter", "Cream"],
    drinks: [
      drink("Champagne", "An entrée + appetizer, appetizer + main, or main + dessert pair", "adjacentCourse"),
      drink("Cognac", "At least 1 dish with 2 Ingredient Cards added", "hardDish"),
      drink("Pernod", "Every served Recipe Card has a different course tag", "differentCourses"),
    ],
  },
  china: {
    id: "china",
    flag: "🇨🇳",
    name: "Jin Long",
    region: "Chinese restaurant",
    monogram: "JL",
    accent: "#c12f32",
    ability: "Double Service",
    abilityText: "Each pair of recipes served grants +1 serve value.",
    promotionText: "Lose the customer with a same-type dish pair; track one recipe.",
    customerEffect: "Easy dishes gain +1 serve value.",
    recipes: [
      recipe("Mapo Tofu", 0),
      recipe("Congee", 0, "rice"),
      recipe("Sticky Rice with Mango", 0, "rice"),
      recipe("Dry-Fried Green Beans", 0),
      recipe("Kung Pao Chicken", 0),
      recipe("Zha Jiang Mian", 0, "noodles"),
      recipe("Soup Noodles with Chicken", 1, "noodles"),
      recipe("Hainanese Chicken Rice", 1, "rice"),
      recipe("Claypot Rice", 1, "rice"),
      recipe("Yangzhou Fried Rice", 1, "rice"),
      recipe("Cantonese Beef Chow Fun", 1, "noodles"),
      recipe("Sichuan Dan Dan Noodles", 1, "noodles"),
      recipe("Lo Mein", 2, "noodles"),
      recipe("Peking Duck Fried Rice", 2, "rice"),
      recipe("Dragon Beard Noodles", 2, "noodles"),
    ],
    ingredients: [
      ingredient("Jasmine Rice", 2),
      ingredient("Wheat Noodles", 2),
      ingredient("Bok Choy", 2),
      ingredient("Chinese Eggplant", 2),
      ingredient("Tofu", 2),
      ingredient("Scallions", 2),
    ],
    flavors: ["Shiitake Mushrooms", "Soy Sauce", "Mung Bean Sprouts"],
    drinks: [
      drink("Baijiu", "At least 1 rice Recipe Card and 1 noodle Recipe Card", "riceAndNoodles"),
      drink("Huangjiu", "At least 2 rice Recipe Cards or 2 noodle Recipe Cards", "sameType"),
      drink("Green Tea", "At least 1 dish with no Ingredient Cards added", "easyDish"),
    ],
  },
  india: {
    id: "india",
    flag: "🇮🇳",
    name: "Raj Mahal",
    region: "Indian restaurant",
    monogram: "RM",
    accent: "#d8781d",
    ability: "Spice Harmony",
    abilityText: "Each distinct pair of different spices gains +1 serve value.",
    promotionText: "Lose the customer with a new spice ingredient; track that spice.",
    customerEffect: "Each pair of added ingredients gains +1 serve value.",
    recipes: [
      recipe("Jeera Rice", 0),
      recipe("Spiced Lentil Soup", 0),
      recipe("Tamarind Rice", 0),
      recipe("Lemon Rice", 0),
      recipe("Chicken Curry", 0),
      recipe("Biryani", 1),
      recipe("Dal Tadka", 1),
      recipe("Masoor Dal", 1),
      recipe("Chana Masala", 1),
      recipe("Aloo Gobi", 1),
      recipe("Paneer Butter Masala", 1),
      recipe("Vegetable Korma", 1),
      recipe("Coconut Curry", 2),
      recipe("Rogan Josh", 2),
      recipe("Malai Kofta", 2),
    ],
    ingredients: [
      ingredient("Cumin", 2, "spice", "cumin"),
      ingredient("Saffron", 2, "spice", "saffron"),
      ingredient("Coriander", 2, "spice", "coriander"),
      ingredient("Cinnamon", 2, "spice", "cinnamon"),
      ingredient("Cardamom", 2, "spice", "cardamom"),
      ingredient("Turmeric", 2, "spice", "turmeric"),
    ],
    flavors: ["Ghee", "Coconut Milk", "Cashew"],
    drinks: [
      drink("Feni", "At least 2 Ingredient Cards added across the meal", "twoIngredients"),
      drink("Lassi", "At least 1 dish with a Flavor Card added", "flavoredDish"),
      drink("Masala Chai", "At least 2 different spice Ingredient Card types", "twoSpices"),
    ],
  },
  usa: {
    id: "usa",
    flag: "🇺🇸",
    name: "Liberty Grill",
    region: "American restaurant",
    monogram: "LG",
    accent: "#257b98",
    ability: "Load It Up",
    abilityText: "Add up to 2 ingredients above printed slots across your meal.",
    promotionText: "Lose the customer with a burger or steak; track that recipe.",
    customerEffect: "Gain +1 for each pair of cards left in hand.",
    recipes: [
      recipe("Lobster Roll", 0),
      recipe("Cornbread", 0),
      recipe("Clam Chowder", 0),
      recipe("Johnny Cakes", 0),
      recipe("Juicy Lucy", 1, "burger"),
      recipe("Classic Cheeseburger", 1, "burger"),
      recipe("Bacon Cheeseburger", 1, "burger"),
      recipe("Green Chile Cheeseburger", 1, "burger"),
      recipe("Philly Cheesesteak", 1, "steak"),
      recipe("Tomahawk Steak", 1, "steak"),
      recipe("Porterhouse Steak", 1, "steak"),
      recipe("Ribeye Steak", 1, "steak"),
      recipe("Deep-fried Burger", 2, "burger"),
      recipe("T-bone Steak", 2, "steak"),
      recipe("Apple Pie", 2),
    ],
    ingredients: [
      ingredient("Cheddar Cheese", 2),
      ingredient("Bacon", 2),
      ingredient("Pickles", 2),
      ingredient("Caramelized Onions", 2),
      ingredient("Lettuce", 2),
      ingredient("Tomato", 2),
    ],
    flavors: ["Ketchup", "Mustard", "Mayo"],
    drinks: [
      drink("Coke", "At least 2 burger Recipe Cards", "twoBurgers"),
      drink("Bourbon", "At least 2 steak Recipe Cards", "twoSteaks"),
      drink(
        "Root Beer",
        "At least 1 dish has more Ingredient Cards than its Recipe Card's printed slots",
        "overstuffed",
      ),
    ],
  },
  turkey: {
    id: "turkey",
    flag: "🇹🇷",
    name: "Sultan Saray",
    region: "Turkish restaurant",
    monogram: "SS",
    accent: "#704a91",
    ability: "Mixed Grill",
    abilityText: "Kebabs gain +1 for each non-kebab dish served with them.",
    promotionText: "Lose the customer with a kebab dish; track that recipe.",
    customerEffect: "Gain +1 if you trail an opponent in tracked Promotion Cards.",
    recipes: [
      recipe("Shish Kebab", 0, "kebab"),
      recipe("Adana Kebab", 0, "kebab"),
      recipe("Iskender Kebab", 0, "kebab"),
      recipe("Ciğer Kebab", 0, "kebab"),
      recipe("Döner Kebab", 0, "kebab"),
      recipe("Beyti Kebab", 0, "kebab"),
      recipe("Patlican Dolmasi", 1),
      recipe("Lahmacun", 1),
      recipe("Pide", 1),
      recipe("Köftesi", 1),
      recipe("Muhammara", 1),
      recipe("Imam Bayildi", 1),
      recipe("Baklava", 2),
      recipe("Turkish Delight", 2),
      recipe("Kadayif", 2),
    ],
    ingredients: [
      ingredient("Lamb", 2),
      ingredient("Eggplant", 2),
      ingredient("Tomato", 2),
      ingredient("Yogurt", 2),
      ingredient("Pistachios", 2),
      ingredient("Bulgur", 2),
    ],
    flavors: ["Sumac", "Paprika", "Pomegranate Juice"],
    drinks: [
      drink("Raki", "At least 1 kebab Recipe Card and 1 non-kebab Recipe Card", "mixedKebab"),
      drink("Salep", "Every served Recipe Card is a kebab", "allKebab"),
      drink("Ayran", "At least 2 non-kebab Recipe Cards", "twoNonKebab"),
    ],
  },
  japan: {
    id: "japan",
    flag: "🇯🇵",
    name: "Sakura House",
    region: "Japanese restaurant",
    monogram: "SH",
    accent: "#9f4e62",
    ability: "Measured Seasoning",
    abilityText: "Use exactly 1 seasoning ingredient in a meal to gain +1.",
    promotionText: "Lose the customer with a new seasoning ingredient; track that seasoning.",
    customerEffect: "Hard dishes gain +1 serve value.",
    recipes: [
      recipe("Shoyu Ramen", 0),
      recipe("Onigiri", 0),
      recipe("Edamame Salad", 0),
      recipe("Tamago Sushi", 0),
      recipe("Miso Ramen", 1),
      recipe("Tonkotsu Ramen", 1),
      recipe("California Roll", 1),
      recipe("Spicy Tuna Roll", 1),
      recipe("Udon Noodles with Tempura", 1),
      recipe("Okonomiyaki", 1),
      recipe("Takoyaki", 1),
      recipe("Unagi Sushi Platter", 2),
      recipe("Omurice", 2),
      recipe("Gyoza", 2),
    ],
    ingredients: [
      ingredient("Dashi Stock", 5),
      ingredient("Umami", 2, "seasoning", "umami"),
      ingredient("Wasabi", 2, "seasoning", "wasabi"),
      ingredient("Ginger", 2, "seasoning", "ginger"),
      ingredient("Garlic", 2, "seasoning", "garlic"),
    ],
    flavors: ["Nori", "Sesame Oil", "Yuzu"],
    drinks: [
      drink("Sake", "A Wasabi Ingredient Card was added", "wasabi"),
      drink("Matcha Tea", "At least 2 differently named Ingredient Cards were added", "twoDifferentIngredients"),
      drink("Umeshu", "At least 1 dish with 2 Ingredient Cards added", "hardDish"),
    ],
  },
  mexico: {
    id: "mexico",
    flag: "🇲🇽",
    name: "El Nopalito",
    region: "Mexican restaurant",
    monogram: "EN",
    accent: "#7b4b2a",
    ability: "Turn Up the Heat",
    abilityText: "Hot ingredients may fill zero-slot recipes; use at most 2 hot ingredients.",
    promotionText: "Lose the customer with a hot ingredient; track that ingredient.",
    customerEffect: "Normal dishes gain +1 serve value.",
    recipes: [
      recipe("Quesadilla", 0),
      recipe("Taco de Frijoles", 0),
      recipe("Chilaquiles Verdes", 0),
      recipe("Carne Asada Tacos", 0),
      recipe("Enchiladas Rojas", 0),
      recipe("Mole Poblano with Rice", 1),
      recipe("Burrito de Frijoles", 1),
      recipe("Chicken Fajitas", 1),
      recipe("Tostadas de Pollo", 1),
      recipe("Pico de Gallo Nachos", 1),
      recipe("Taco al Pastor", 1),
      recipe("Pozole Rojo", 2),
      recipe("Chiles Rellenos", 2),
      recipe("Tamales", 2),
    ],
    ingredients: [
      ingredient("Cayenne Pepper", 1, "hot", "cayenne"),
      ingredient("Chipotle", 1, "hot", "chipotle"),
      ingredient("Habanero", 1, "hot", "habanero"),
      ingredient("Serrano", 1, "hot", "serrano"),
      ingredient("Jalapeño", 1, "hot", "jalapeno"),
      ingredient("Poblano", 1, "hot", "poblano"),
      ingredient("Avocado", 4),
      ingredient("Corn", 3),
    ],
    flavors: ["Lime", "Cilantro", "Sour Cream"],
    drinks: [
      drink("Mezcal", "At least 1 hot Ingredient Card was added", "oneHot"),
      drink("Tequila", "At least 2 hot Ingredient Cards were added", "twoHot"),
      drink("Tepache", "At least 1 dish with exactly 1 Ingredient Card and a Flavor Card added", "normalFlavor"),
    ],
  },
};

export const CUISINE_LIST = Object.values(CUISINES);

export const TYPE_META = {
  recipe: { label: "Recipe", symbol: "♨", value: "+1" },
  ingredient: { label: "Ingredient", symbol: "◇", value: "+1" },
  flavor: { label: "Flavor", symbol: "✦", value: "+2" },
  drink: { label: "Drink", symbol: "◒", value: "+3" },
};
